"""empty message

Revision ID: 0102233fc0ba
Revises: e988a6929d8d
Create Date: 2025-01-31 19:58:15.271024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0102233fc0ba'
down_revision: Union[str, None] = 'e988a6929d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes_lists',
    sa.Column('wishes_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wishes_list_id')
    )
    op.create_table('armored_wishes',
    sa.Column('armored_wish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['users_wishes.wish_id'], ),
    sa.PrimaryKeyConstraint('armored_wish_id')
    )
    op.create_table('wishes_in_list',
    sa.Column('wishes_in_list_id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['wishes_lists.wishes_list_id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['users_wishes.wish_id'], ),
    sa.PrimaryKeyConstraint('wishes_in_list_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes_in_list')
    op.drop_table('armored_wishes')
    op.drop_table('wishes_lists')
    # ### end Alembic commands ###
