"""empty message

Revision ID: 10ffdb33fba8
Revises: 
Create Date: 2025-06-21 12:55:05.603218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ffdb33fba8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('completed_wishes',
    sa.Column('complete_wish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish_title', sa.String(), nullable=False),
    sa.Column('wish_price', sa.Float(), nullable=False),
    sa.Column('wish_source_url', sa.String(), nullable=True),
    sa.Column('wish_photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('complete_wish_id')
    )
    op.create_table('subscriptions',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_profile_id')
    )
    op.create_table('users_wishes',
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('wish_photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wish_id')
    )
    op.create_table('wishes_lists',
    sa.Column('wishes_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wishes_list_id')
    )
    op.create_table('armored_wishes',
    sa.Column('armored_wish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['users_wishes.wish_id'], ),
    sa.PrimaryKeyConstraint('armored_wish_id')
    )
    op.create_table('wishes_in_list',
    sa.Column('wishes_in_list_id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['wishes_lists.wishes_list_id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['users_wishes.wish_id'], ),
    sa.PrimaryKeyConstraint('wishes_in_list_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes_in_list')
    op.drop_table('armored_wishes')
    op.drop_table('wishes_lists')
    op.drop_table('users_wishes')
    op.drop_table('user_profiles')
    op.drop_table('subscriptions')
    op.drop_table('completed_wishes')
    op.drop_table('users')
    # ### end Alembic commands ###
