"""empty message

Revision ID: 3a4cb1e4e10b
Revises: 9cd8e1b5661a
Create Date: 2025-01-24 13:42:38.501313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4cb1e4e10b'
down_revision: Union[str, None] = '9cd8e1b5661a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_wishes', sa.Column('is_secret', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_wishes', 'is_secret')
    # ### end Alembic commands ###
