version: '3.9'

services:

  mydreams_db:
    container_name: mydreams_db
    image: postgres:16.4
    restart: always    
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 6020:5432
    volumes:
      - /var/lib/postgresql/data

  mydreams_api:
    container_name: mydreams_api
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    restart: always
    command: ["poetry", "run", "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - ${API_BASE_PORT}:8000
    
    depends_on:
      - speedsolver.database

